# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Scanner Tests

on:
  push:
    branches: [ main ]
    paths:
      - "Tools/scanner/**"
  pull_request:
    branches: [ main ]
    paths:
      - "Tools/scanner/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Read .nvmrc
      working-directory: ./Tools/scanner
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - run: npm ci
      working-directory: ./Tools/scanner
    - run: npm run build
      working-directory: ./Tools/scanner
    - run: npm test
      working-directory: ./Tools/scanner
